language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: bw+n/P1NOXA3yj5cG3Z65ceB6+pGcdM6cp95Yho8bmQVKPtRwq4PEv1ryY1/XlUMLw3465ESXPH9rZlZUs3Of1G2ArkCacngx7BnOutKbE2OoxGZHpPfW9TDobHS2OfuE6quqhsJB/LSDZflwPyqbPrpdsd3aD0f8ZOfgVkpFe2+K0n/hm73fDmGbfnNIZtsLynA7xR6ukFRbhS0aLc21KheDsM41gbxS8X3DY0pe6JYm87GraSZrCmftt/xDcWOtB5U2GyoPqLXTasZdtW7fu3HVbI8GzjWLvRjMocrnfQCAzomvAvElCufppWPE6YWtGrQIo1KOj07ibOsDv2mWnTmuDpLKkebhKEbQNySL1hyiHCe0t964/QwiYDnqQXz1CauhMKPlH1S7LMzDs9uC/DpgcdLuCPHkTu91NP9U5eWzC6ECZQ0R9rMamekhQRTpnyn66CpfKMqLvnsEHlG9o0vxzIZohyt2IJH5l3zB7A/BVE+sULDcVQPBdyQeYnIEhs1HQ9RFdhOZn/4YsW2CWOfe7lCzgppPaUkStSKpLiu1Fa3Tul3UmDCgCDW5bCOXtB7uLU0fX07aGHaqIjShfe04TUoG9qsSWM4au9Fet0GEvadY6Jb1oam5kLEe8ihHtd49Jd1ZBCph92sZ8nzCv51aqJk0Fz1PjamkxmU3aU=
