language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: X/wFsru+NWULMvQ0F04hkACyoQ1e4r3rPbtc/n005tRITaoQ/FFooOM7AtptQrxpZAbG7Amn0fxTzAwA9WkRjH8Rnx4aWacFAR91Wy2n1w2j5z+AivByuhM7Tp0m3CL4bUCr01XVWciDY7HQiGlGrwmuBWDM5fy78YhwcAc/8pzgEQ5fvy2Pc+QtRY7WsgmTVAzdvOFcoqZdAeffKed8kCsQNPT3wjShDmLDKqFsCFTrXLcGjBBaWlkv6qFWIeIieIAWsgdls8PmOD6BRJxf8YyFcnyqX2nGq+OvjjdJIaLce6/sCmX/KhRxbjGhUDPNwfLf9sYFTEqHLAtqtxd4W/MWVRr+9VXxI/i2J1IareznL1Q6TQiO1vJcNyptkg8fCUGosA4wIi5ktzZT6c7aPeFw/Y2EPutDsIsD1G54ypxgqdvtpeWgtuH2CYm6da8/ANR6uFORVn7CTqmKmxzYkKGu88uLOkG61uWOMEnHLng8ml/auxP1mnb86GoOmBJugWCB3Ul3sX/S6h4lMIeN6nApBzcfDbYNxTf4fL1QEeIBt+/bWSuqiGgxF34XGP4UGyLQ6XF90as0efCwDw3VMnUv3SOHn90mKWUkETys3fTVbIIqHxMMNXdd95Ja17Cs1chNCxwuW6gMdURe1nN5qQUturjOI2LfrjkhPjv0n2U=evan058@gmail.com
